function htmlSource = jsBackDoorHTMLSource()

    htmlSource = sprintf(['<!DOCTYPE html>\n'  ...
                          '<html>\n'          ...
                            '<head>\n'        ...
                                '<script>\n'  ...
                                    '%s\n'    ...
                                '</script>\n' ...
                            '</head>\n\n'     ...
                            '<body>\n'        ...
                            '</body>\n'       ...
                          '</html>'], fileread(fullfile(ccTools.Path, 'css&js', 'compCustomization.js')));

end