classdef (Abstract) indexedDB

    properties (Constant)
        %-----------------------------------------------------------------%
        DB_NAME    = 'anatelWebAppsCache'
        DB_VERSION = 1
    end


    methods (Static = true)
        %-----------------------------------------------------------------%
        function store = DB_STORE(appName)
            store = [appName 'Cache'];
        end

        %-----------------------------------------------------------------%
        function openDB(jsBackDoor, appName)
            sendEventToHTMLSource(jsBackDoor, 'indexedDB', struct( ...
                'operation', 'openDB', ...
                'name', appEngine.indexedDB.DB_NAME, ...
                'version', appEngine.indexedDB.DB_VERSION, ...
                'store', appEngine.indexedDB.DB_STORE(appName) ...
            ))
        end

        %-----------------------------------------------------------------%
        function saveData(jsBackDoor, appName, key, data)
            sendEventToHTMLSource(jsBackDoor, 'indexedDB', struct( ...
                'operation', 'saveData', ...
                'store', appEngine.indexedDB.DB_STORE(appName), ...
                'key', key, ...
                'data', data ...
            ))
        end

        %-----------------------------------------------------------------%
        function loadData(jsBackDoor, appName, key)
            sendEventToHTMLSource(jsBackDoor, 'indexedDB', struct( ...
                'operation', 'loadData', ...
                'store', appEngine.indexedDB.DB_STORE(appName), ...
                'key', key ...
            ))
        end

        %-----------------------------------------------------------------%
        function deleteData(jsBackDoor, appName, key)
            sendEventToHTMLSource(jsBackDoor, 'indexedDB', struct( ...
                'operation', 'deleteData', ...
                'store', appEngine.indexedDB.DB_STORE(appName), ...
                'key', key ...
            ))
        end
    end

end