classdef DownloadPanel < handle

    % DOWNLOADPANEL Reusable asynchronous download queue UI.
    %
    % DownloadPanel owns the presentation and lifecycle of multiple download
    % rows: the download avatar, the popup panel, progress aggregation,
    % pause/resume/cancel controls, conflict decisions, and cleanup of UI and
    % downloader handles. It deliberately does not know how authentication
    % or network transfer is implemented.
    %
    % The caller supplies DownloaderFactory. The factory receives a normalized
    % request containing the URL, temporary and target folders, file name,
    % task-scoped staging paths, and conflict actions. It must return an
    % object exposing start, pause, resume, stop, ProgressFcn, CompletedFcn,
    % and ErrorFcn.
    %
    % Temporary files are written below TempPath. Completed files are written
    % below TargetPath. Existing target and partial-file conflicts are shown
    % in the download row instead of being handled by modal dialogs.

    properties
        executionMode (1,:) char = 'MATLABEnvironment'
        TempPath (1,:) char = ''
        TargetPath (1,:) char = ''
        CollisionPolicy (1,:) char = 'askInRow'
        PartialConflictPolicy (1,:) char = 'askInRow'
        CompletedFcn = []
        ErrorFcn = []
    end

    properties (SetAccess = private)
        AvatarHTML
        DownloaderFactory
        DestinationResolver
        Manager
    end

    properties (Access = private)
        ParentContainer
        UIFigure
        DownloadDialog
        DownloadHeader
        DownloadTitleLabel
        CloseImage
        DownloadContent
        DownloadStack
        DownloadTasks = {}
        DownloadOrder = []
        DownloadFileNames cell = cell(0, 2)
        AvatarHTMLReady (1,1) logical = false
        AvatarState struct = struct('level', 0, ...
                                    'inProgress', false, ...
                                    'ballCount', 0, ...
                                    'speedRadiansPerSecond', 0)
        OriginalWindowButtonDownFcn = []
        IsDeleting (1,1) logical = false
    end


    methods
        %-----------------------------------------------------------------%
        function obj = DownloadPanel(parentContainer, options)
            % DOWNLOADPANEL Construct a download panel attached to a UI parent.
            %
            % PARENTCONTAINER is a UI container belonging to a figure.
            % DOWNLOADERFACTORY is a function handle that creates one
            % downloader object from the normalized request generated by the
            % panel. Optional name-value arguments configure execution mode,
            % temporary and target folders, and conflict policies.
            arguments
                parentContainer
                options.DownloaderFactory (1,1) function_handle
                options.executionMode (1,:) char = 'MATLABEnvironment'
                options.tempPath (1,:) char = tempdir
                options.targetPath (1,:) char = ''
                options.CollisionPolicy (1,:) char = 'askInRow'
                options.PartialConflictPolicy (1,:) char = 'askInRow'
                options.DestinationResolver = []
            end

            obj.ParentContainer = parentContainer;
            obj.UIFigure = findFigure(parentContainer);
            if isempty(obj.UIFigure) || ~isvalid(obj.UIFigure)
                error('ui:DownloadPanel:invalidParent', ...
                      'The parent container must belong to a valid figure.')
            end

            obj.DownloaderFactory = options.DownloaderFactory;
            if ~isempty(options.DestinationResolver) && ...
                    ~isa(options.DestinationResolver, 'function_handle')
                error('ui:DownloadPanel:invalidDestinationResolver', ...
                      'DestinationResolver must be a function handle or empty.')
            end
            obj.DestinationResolver = options.DestinationResolver;
            obj.executionMode = options.executionMode;
            obj.TempPath = char(options.tempPath);
            obj.TargetPath = char(options.targetPath);
            obj.CollisionPolicy = options.CollisionPolicy;
            obj.PartialConflictPolicy = options.PartialConflictPolicy;
            obj.Manager = download.DownloadManager(...
                'DownloaderFactory', obj.DownloaderFactory, ...
                'CollisionPolicy', obj.CollisionPolicy, ...
                'PartialConflictPolicy', obj.PartialConflictPolicy);
            obj.Manager.SnapshotFcn = @(snapshot) obj.onManagerSnapshot(snapshot);
            obj.Manager.TaskReorderedFcn = @(snapshot) obj.onManagerTaskReordered(snapshot);
            obj.Manager.CompletedFcn = @(taskID, info, snapshot) ...
                obj.onManagerCompleted(taskID, info, snapshot);
            obj.Manager.ErrorFcn = @(taskID, exception, snapshot) ...
                obj.onManagerError(taskID, exception, snapshot);

            obj.AvatarHTML = uihtml(parentContainer);
            obj.AvatarHTML.HTMLSource = avatarHTMLPath();
            obj.AvatarHTML.HTMLEventReceivedFcn = @(~, event) obj.onAvatarEvent(event);

            obj.OriginalWindowButtonDownFcn = obj.UIFigure.WindowButtonDownFcn;
            obj.UIFigure.WindowButtonDownFcn = @(source, event) obj.onFigureButtonDown(source, event);
        end

        %-----------------------------------------------------------------%
        function delete(obj)
            % DELETE Stop active downloads and release panel-owned UI handles.
            if obj.IsDeleting
                return
            end
            obj.IsDeleting = true;

            if ~isempty(obj.Manager) && isvalid(obj.Manager)
                delete(obj.Manager)
            end
            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if ~isempty(task)
                    obj.deleteTaskGraphics(task)
                end
            end
            obj.DownloadTasks = {};
            obj.DownloadOrder = [];
            obj.closeDownloadContainer()

            if ~isempty(obj.AvatarHTML) && isvalid(obj.AvatarHTML)
                delete(obj.AvatarHTML)
            end
            if ~isempty(obj.UIFigure) && isvalid(obj.UIFigure)
                obj.UIFigure.WindowButtonDownFcn = obj.OriginalWindowButtonDownFcn;
            end
        end

        %-----------------------------------------------------------------%
        function taskID = addDownload(obj, url)
            % ADDDOWNLOAD Add and start a download for a URL.
            %
            % The file name is derived from URL. Depending on executionMode,
            % the target is resolved directly or through a file-selection
            % dialog. The method returns the numeric task identifier, or an
            % empty value when the user cancels destination selection.
            arguments
                obj
                url (1,:) char {mustBeNonempty}
            end

            url = char(url);
            [finalPath, cancelled, allowSourceFilename] = obj.resolveFinalPath(url);
            if cancelled
                taskID = [];
                return
            end

            [targetFolder, fileName, extension] = fileparts(finalPath);
            fileName = [fileName, extension];
            request = struct('URL', url, ...
                             'TempFolder', obj.TempPath, ...
                             'TargetFolder', targetFolder, ...
                             'FileName', fileName, ...
                             'FinalPath', finalPath, ...
                             'AllowSourceFilename', allowSourceFilename);
            taskID = obj.Manager.addDownload(request);
        end

        %-----------------------------------------------------------------%
        function show(obj)
            % SHOW Make the download popup visible and bring it to the front.
            if isempty(obj.DownloadDialog) || ~isvalid(obj.DownloadDialog)
                return
            end
            obj.DownloadDialog.Visible = 'on';
            drawnow
            obj.positionDownloadContainer()
            uistack(obj.DownloadDialog, 'top')
        end

        %-----------------------------------------------------------------%
        function hide(obj)
            % HIDE Hide the download popup without stopping its downloads.
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog)
                obj.DownloadDialog.Visible = 'off';
            end
        end

        %-----------------------------------------------------------------%
        function cancel(obj, taskID)
            % CANCEL Stop one download, remove temporary files, and remove its row.
            task = obj.getTask(taskID);
            if isempty(task)
                return
            end

            obj.Manager.cancel(taskID)
        end

        %-----------------------------------------------------------------%
        function cancelAll(obj)
            % CANCELALL Cancel every download and remove temporary files.
            obj.Manager.cancelAll()
        end

        %-----------------------------------------------------------------%
        function tf = isActive(obj, filePath)
            % ISACTIVE Return true when a task targets filePath.
            tf = obj.Manager.isActive(filePath);
        end

        %-----------------------------------------------------------------%
        function setCollisionPolicy(obj, value)
            % SETCOLLISIONPOLICY Update the panel and manager policies together.
            obj.CollisionPolicy = value;
            if ~isempty(obj.Manager) && isvalid(obj.Manager)
                obj.Manager.CollisionPolicy = obj.CollisionPolicy;
            end
        end
    end


    % Private implementation: HTML events, task state, row controls, layout,
    % conflict handling, and aggregate avatar updates.
    methods (Access = private)
        %-----------------------------------------------------------------%
        function onManagerSnapshot(obj, snapshot)
            if isempty(snapshot) || obj.IsDeleting
                return
            end

            taskID = snapshot.ID;
            if strcmp(snapshot.LifecycleState, 'canceled')
                obj.removeTask(taskID)
                return
            end
            task = obj.getTask(taskID);
            if isempty(task)
                task = obj.createTaskGraphics(taskID, snapshot.FileName);
                task.Snapshot = snapshot;
                obj.DownloadTasks{taskID} = task;
                obj.DownloadOrder(end+1) = taskID;
            else
                task.Snapshot = snapshot;
                obj.DownloadTasks{taskID} = task;
            end
            obj.renderTask(snapshot)
            obj.refreshDownloadContainer()
            obj.updateDownloadAvatar()
            if strcmp(snapshot.LifecycleState, 'awaitingConflictDecision')
                obj.show()
            end
        end

        %-----------------------------------------------------------------%
        function onManagerTaskReordered(obj, snapshot)
            if isempty(snapshot) || obj.IsDeleting || isempty(obj.getTask(snapshot.ID))
                return
            end
            obj.DownloadOrder(obj.DownloadOrder == snapshot.ID) = [];
            obj.DownloadOrder(end+1) = snapshot.ID;
            obj.refreshDownloadContainer()
            obj.show()
        end

        %-----------------------------------------------------------------%
        function onManagerCompleted(obj, taskID, info, snapshot)
            obj.removeTask(taskID)
            invokeCallback(obj.CompletedFcn, taskID, info, snapshot)
        end

        %-----------------------------------------------------------------%
        function onManagerError(obj, taskID, exception, snapshot)
            obj.removeTask(taskID)
            invokeCallback(obj.ErrorFcn, taskID, exception, snapshot)
        end

        %-----------------------------------------------------------------%
        function renderTask(obj, snapshot)
            task = obj.getTask(snapshot.ID);
            if isempty(task)
                return
            end
            task.Snapshot = snapshot;
            task.StatusLabel.Text = snapshot.FileName;
            elapsedSeconds = snapshotElapsedSeconds(snapshot);
            task.BytesLabel.Text = progressText(snapshot.ReceivedBytes, ...
                                                snapshot.TotalBytes, ...
                                                elapsedSeconds, ...
                                                snapshot.TransferRate);
            task.ProgressFraction = snapshot.ProgressFraction;
            task.Snapshot = snapshot;

            if strcmp(snapshot.LifecycleState, 'awaitingConflictDecision')
                obj.renderConflict(task, snapshot)
            else
                task.ConflictPanel.Visible = 'off';
                task.PauseButton.Visible = 'on';
                task.CancelButton.Visible = 'on';
                task.GridLayout.RowHeight = {24, 20, 46, 30, 1};
                task.RowHeight = 154;
                if strcmp(snapshot.LifecycleState, 'paused')
                    task.PauseButton.Text = 'Resume';
                else
                    task.PauseButton.Text = 'Pause';
                end
                if ismember(snapshot.LifecycleState, {'stopped', 'completed', 'failed', 'canceled'})
                    task.PauseButton.Visible = 'off';
                    task.CancelButton.Visible = 'off';
                    task.StatusLabel.Text = sprintf('%s (%s)', snapshot.FileName, ...
                                                    snapshot.LifecycleState);
                end
            end
            obj.DownloadTasks{snapshot.ID} = task;
            obj.updateProgressScale(task)
        end

        %-----------------------------------------------------------------%
        function renderConflict(obj, task, snapshot)
            if strcmp(snapshot.ConflictType, 'target')
                task.StatusLabel.Text = sprintf('%s already exists', snapshot.FileName);
                task.BytesLabel.Text = 'Choose an action to continue.';
                actionLabels = {'Overwrite', 'Save as new', 'Cancel'};
                actions = {'overwrite', 'uniqueName', 'cancel'};
            else
                task.StatusLabel.Text = sprintf('Partial download found for %s', snapshot.FileName);
                task.BytesLabel.Text = 'Resume, restart, or cancel this download.';
                actionLabels = {'Resume', 'Restart', 'Cancel'};
                actions = {'resume', 'restart', 'cancel'};
            end
            for buttonIndex = 1:numel(task.ConflictButtons)
                task.ConflictButtons(buttonIndex).Text = actionLabels{buttonIndex};
                task.ConflictButtons(buttonIndex).ButtonPushedFcn = ...
                    @(~, ~) obj.Manager.resolveConflict(snapshot.ID, actions{buttonIndex});
                task.ConflictButtons(buttonIndex).Enable = 'on';
            end
            task.ConflictPanel.Visible = 'on';
            task.PauseButton.Visible = 'off';
            task.CancelButton.Visible = 'off';
            task.GridLayout.RowHeight = {24, 20, 46, 30, 30};
            task.RowHeight = 190;
        end

        %-----------------------------------------------------------------%
        function onAvatarEvent(obj, event)
            eventName = eventProperty(event, {'HTMLEventName', 'EventName'});
            payload = eventProperty(event, {'HTMLEventData', 'Data'});
            if ischar(payload) || (isstring(payload) && isscalar(payload))
                try
                    payload = jsondecode(char(payload));
                catch
                    payload = struct();
                end
            end

            if strcmp(eventName, 'downloadAvatarReady') || ...
                    (isstruct(payload) && isfield(payload, 'type') && strcmp(string(payload.type), 'ready'))
                obj.AvatarHTMLReady = true;
                obj.AvatarHTML.Data = obj.AvatarState;
                return
            end

            if strcmp(eventName, 'downloadAvatarClick') || ...
                    (isstruct(payload) && isfield(payload, 'type') && strcmp(string(payload.type), 'click'))
                obj.show()
            end
        end

        %-----------------------------------------------------------------%
        function onFigureButtonDown(obj, source, event)
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog) && ...
                    strcmp(obj.DownloadDialog.Visible, 'on')
                point = obj.UIFigure.CurrentPoint;
                panelPosition = obj.DownloadDialog.Position;
                insidePanel = point(1) >= panelPosition(1) && ...
                              point(1) <= panelPosition(1) + panelPosition(3) && ...
                              point(2) >= panelPosition(2) && ...
                              point(2) <= panelPosition(2) + panelPosition(4);
                if ~insidePanel
                    obj.hide()
                end
            end
            invokeCallback(obj.OriginalWindowButtonDownFcn, source, event)
        end

        %-----------------------------------------------------------------%
        function task = createTaskGraphics(obj, taskID, fileName)
            obj.ensureDownloadContainer()

            task = struct('ID', taskID, ...
                          'FileName', fileName, ...
                          'ProgressFraction', 0, ...
                          'Dialog', [], ...
                          'Separator', [], ...
                          'GridLayout', [], ...
                          'StatusLabel', [], ...
                          'BytesLabel', [], ...
                          'ProgressTrack', [], ...
                          'ProgressFill', [], ...
                          'ProgressMarkers', [], ...
                          'PauseButton', [], ...
                          'CancelButton', [], ...
                          'ConflictPanel', [], ...
                          'ConflictButtons', [], ...
                          'RowHeight', 154, ...
                          'Snapshot', struct());

            task.Dialog = uipanel(obj.DownloadStack, ...
                                  'BorderType', 'none', ...
                                  'BackgroundColor', obj.UIFigure.Color);
            task.Separator = uipanel(obj.DownloadStack, ...
                                     'BorderType', 'none', ...
                                     'BackgroundColor', [0.55, 0.55, 0.55], ...
                                     'Visible', 'off');
            task.GridLayout = uigridlayout(task.Dialog, [5, 3]);
            task.GridLayout.Padding = [16, 12, 16, 8];
            task.GridLayout.RowSpacing = 4;
            task.GridLayout.RowHeight = {24, 20, 46, 30, 1};
            task.GridLayout.ColumnWidth = {'1x', 90, 90};

            task.StatusLabel = uilabel(task.GridLayout, ...
                                       'Text', fileName, ...
                                       'HorizontalAlignment', 'left', ...
                                       'VerticalAlignment', 'bottom', ...
                                       'WordWrap', 'on');
            task.StatusLabel.Layout.Row = 1;
            task.StatusLabel.Layout.Column = [1, 3];

            task.ProgressTrack = uipanel(task.GridLayout, ...
                                         'BorderType', 'none', ...
                                         'BackgroundColor', obj.UIFigure.Color);
            task.ProgressTrack.Layout.Row = 2;
            task.ProgressTrack.Layout.Column = [1, 3];

            task.ProgressFill = uipanel(task.ProgressTrack, ...
                                        'BorderType', 'none', ...
                                        'BackgroundColor', [0, 0.447, 0.741], ...
                                        'Units', 'pixels', ...
                                        'Position', [0, 0, 0, 1]);
            task.ProgressMarkers = gobjects(1, 5);
            for markerIndex = 1:numel(task.ProgressMarkers)
                task.ProgressMarkers(markerIndex) = uipanel(task.ProgressTrack, ...
                                                             'BorderType', 'none', ...
                                                             'BackgroundColor', [0.45, 0.45, 0.45], ...
                                                             'Units', 'pixels', ...
                                                             'Position', [0, 0, 1, 1]);
            end

            task.BytesLabel = uilabel(task.GridLayout, 'Text', '', 'WordWrap', 'on');
            task.BytesLabel.Layout.Row = 3;
            task.BytesLabel.Layout.Column = [1, 3];

            task.PauseButton = uibutton(task.GridLayout, ...
                                        'Text', 'Pause', ...
                                        'ButtonPushedFcn', @(~, ~) obj.togglePause(taskID));
            task.PauseButton.Layout.Row = 4;
            task.PauseButton.Layout.Column = 2;

            task.CancelButton = uibutton(task.GridLayout, ...
                                         'Text', 'Cancel', ...
                                         'ButtonPushedFcn', @(~, ~) obj.cancel(taskID));
            task.CancelButton.Layout.Row = 4;
            task.CancelButton.Layout.Column = 3;

            task.ConflictPanel = uipanel(task.GridLayout, ...
                                         'BorderType', 'none', ...
                                         'Visible', 'off');
            task.ConflictPanel.Layout.Row = 5;
            task.ConflictPanel.Layout.Column = [1, 3];
            conflictLayout = uigridlayout(task.ConflictPanel, [1, 3]);
            conflictLayout.Padding = [0, 0, 0, 0];
            conflictLayout.ColumnWidth = {'1x', '1x', '1x'};
            task.ConflictButtons = gobjects(1, 3);
            task.ConflictButtons(1) = uibutton(conflictLayout, ...
                                               'Text', 'Overwrite', ...
                                               'ButtonPushedFcn', @(~, ~) obj.Manager.resolveConflict(taskID, 'overwrite'));
            task.ConflictButtons(2) = uibutton(conflictLayout, ...
                                               'Text', 'Save as new', ...
                                               'ButtonPushedFcn', @(~, ~) obj.Manager.resolveConflict(taskID, 'uniqueName'));
            task.ConflictButtons(3) = uibutton(conflictLayout, ...
                                               'Text', 'Cancel', ...
                                               'ButtonPushedFcn', @(~, ~) obj.Manager.resolveConflict(taskID, 'cancel'));
            drawnow
            obj.updateProgressScale(task)
        end

        %-----------------------------------------------------------------%
        %-----------------------------------------------------------------%
        function togglePause(obj, taskID)
            task = obj.getTask(taskID);
            if isempty(task) || ~isfield(task, 'Snapshot') || isempty(fieldnames(task.Snapshot))
                return
            end

            if strcmp(task.Snapshot.LifecycleState, 'paused')
                obj.Manager.resume(taskID)
            elseif strcmp(task.Snapshot.LifecycleState, 'active')
                obj.Manager.pause(taskID)
            else
                return
            end
        end

        %-----------------------------------------------------------------%
        function removeTask(obj, taskID)
            task = obj.getTask(taskID);
            if isempty(task)
                return
            end
            obj.deleteTaskGraphics(task)
            obj.DownloadTasks{taskID} = [];
            obj.DownloadOrder(obj.DownloadOrder == taskID) = [];
            obj.refreshDownloadContainer()
            obj.updateDownloadAvatar()
        end

        %-----------------------------------------------------------------%
        function task = getTask(obj, taskID)
            task = [];
            if ~isscalar(taskID) || taskID < 1 || taskID > numel(obj.DownloadTasks)
                return
            end
            task = obj.DownloadTasks{taskID};
            if isempty(task)
                task = [];
            end
        end

        %-----------------------------------------------------------------%
        function deleteTaskGraphics(~, task)
            handles = {task.Dialog, task.Separator};
            for handleIndex = 1:numel(handles)
                handle = handles{handleIndex};
                try
                    if ~isempty(handle) && isvalid(handle)
                        delete(handle)
                    end
                catch
                end
            end
        end

        %-----------------------------------------------------------------%
        function ensureDownloadContainer(obj)
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog)
                return
            end

            obj.DownloadDialog = uipanel(obj.UIFigure, ...
                                         'Title', '', ...
                                         'Visible', 'off', ...
                                         'Scrollable', 'off', ...
                                         'Units', 'pixels', ...
                                         'BorderType', 'line', ...
                                         'BackgroundColor', obj.UIFigure.Color);
            obj.DownloadHeader = uipanel(obj.DownloadDialog, ...
                                         'BorderType', 'none', ...
                                         'BackgroundColor', obj.UIFigure.Color);
            obj.DownloadTitleLabel = uilabel(obj.DownloadHeader, ...
                                             'Text', 'Downloads', ...
                                             'FontWeight', 'bold', ...
                                             'HorizontalAlignment', 'left', ...
                                             'VerticalAlignment', 'center');
            obj.CloseImage = uiimage(obj.DownloadHeader, ...
                                     'ImageSource', closeIconPath(), ...
                                     'ImageClickedFcn', @(~, ~) obj.hide());
            obj.DownloadContent = uipanel(obj.DownloadDialog, ...
                                          'BorderType', 'none', ...
                                          'Units', 'pixels', ...
                                          'BackgroundColor', obj.UIFigure.Color);
            obj.DownloadStack = uigridlayout(obj.DownloadContent, [1, 1]);
            obj.DownloadStack.Padding = [0, 0, 0, 0];
            obj.DownloadStack.RowSpacing = 0;
            obj.DownloadStack.ColumnWidth = {'1x'};
            obj.DownloadStack.RowHeight = {154};
            obj.positionDownloadContainer()
        end

        %-----------------------------------------------------------------%
        function closeDownloadContainer(obj)
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog)
                delete(obj.DownloadDialog)
            end
            obj.DownloadDialog = [];
            obj.DownloadContent = [];
            obj.DownloadStack = [];
        end

        %-----------------------------------------------------------------%
        function refreshDownloadContainer(obj)
            if isempty(obj.DownloadDialog) || ~isvalid(obj.DownloadDialog)
                return
            end

            activeIDs = obj.DownloadOrder;
            isValidTask = false(size(activeIDs));
            for taskIndex = 1:numel(activeIDs)
                task = obj.getTask(activeIDs(taskIndex));
                isValidTask(taskIndex) = ~isempty(task) && ...
                    ~isempty(task.Dialog) && isvalid(task.Dialog);
            end
            activeIDs = activeIDs(isValidTask);
            obj.DownloadOrder = activeIDs;

            if isempty(activeIDs)
                obj.closeDownloadContainer()
                return
            end

            activeIDs = fliplr(activeIDs);
            rowHeights = repmat({1}, 1, 2*numel(activeIDs));
            for row = 1:numel(activeIDs)
                task = obj.DownloadTasks{activeIDs(row)};
                rowHeights{2*row - 1} = task.RowHeight;
                task.Dialog.Layout.Row = 2*row - 1;
                task.Dialog.Layout.Column = 1;
                task.Separator.Layout.Row = 2*row;
                task.Separator.Layout.Column = 1;
                task.Separator.Visible = ternary(row < numel(activeIDs), 'on', 'off');
            end
            obj.DownloadStack.RowHeight = rowHeights;
            obj.positionDownloadContainer()
            obj.resizeDownloadProgressBars()
        end

        %-----------------------------------------------------------------%
        function positionDownloadContainer(obj)
            if isempty(obj.DownloadDialog) || ~isvalid(obj.DownloadDialog) || ...
                    isempty(obj.AvatarHTML) || ~isvalid(obj.AvatarHTML)
                return
            end

            drawnow limitrate
            avatarPosition = getpixelposition(obj.AvatarHTML, true);
            figurePosition = obj.UIFigure.Position;
            figureWidth = figurePosition(3);
            figureHeight = figurePosition(4);
            panelWidth = min(560, max(220, figureWidth - 16));
            headerHeight = 24;
            borderInset = 2;
            panelGap = 12;
            activeHeight = 0;
            for orderIndex = 1:numel(obj.DownloadOrder)
                task = obj.getTask(obj.DownloadOrder(orderIndex));
                if ~isempty(task)
                    activeHeight = activeHeight + task.RowHeight + 1;
                end
            end
            contentHeight = max(1, activeHeight);
            requiredPanelHeight = contentHeight + headerHeight + 2 * borderInset;
            availablePanelHeight = min(avatarPosition(2) - panelGap - 8, figureHeight - 16);
            panelHeight = min(max(64, requiredPanelHeight), max(64, availablePanelHeight));
            panelX = min(max(8, avatarPosition(1)), max(8, figureWidth - panelWidth - 8));
            panelY = avatarPosition(2) - panelHeight - panelGap;
            panelY = min(max(8, panelY), max(8, figureHeight - panelHeight - 8));

            obj.DownloadDialog.Position = [panelX, panelY, panelWidth, panelHeight];
            innerPosition = obj.DownloadDialog.InnerPosition;
            needsVerticalScroll = contentHeight > innerPosition(4);
            obj.DownloadDialog.Scrollable = ternary(needsVerticalScroll, 'on', 'off');
            drawnow limitrate
            innerPosition = obj.DownloadDialog.InnerPosition;
            contentWidth = max(1, floor(innerPosition(3)) - 16 - 2 * borderInset);
            obj.DownloadContent.Position = [borderInset, borderInset, contentWidth, contentHeight];
            obj.DownloadHeader.Position = [borderInset, contentHeight + borderInset, contentWidth, headerHeight];
            obj.DownloadTitleLabel.Position = [8, 0, max(1, contentWidth - 32), headerHeight];
            closeIconSize = 16;
            closeIconMargin = 4;
            obj.CloseImage.Position = [max(closeIconMargin, contentWidth - closeIconSize - closeIconMargin), ...
                                       max(closeIconMargin, (headerHeight - closeIconSize) / 2), ...
                                       closeIconSize, closeIconSize];
        end

        %-----------------------------------------------------------------%
        function resizeDownloadProgressBars(obj)
            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if isempty(task) || isempty(task.ProgressTrack) || ~isvalid(task.ProgressTrack)
                    continue
                end
                obj.updateProgressScale(task)
            end
        end

        %-----------------------------------------------------------------%
        function updateProgressScale(~, task)
            if isempty(task.ProgressTrack) || ~isvalid(task.ProgressTrack)
                return
            end
            trackSize = task.ProgressTrack.InnerPosition;
            trackWidth = max(0, trackSize(3));
            trackHeight = max(1, trackSize(4));
            task.ProgressFill.Position = [0, 0, task.ProgressFraction * trackWidth, trackHeight];
            markerWidth = 1;
            markerXPositions = round((0:4) / 4 * max(0, trackWidth - markerWidth));
            for markerIndex = 1:numel(task.ProgressMarkers)
                marker = task.ProgressMarkers(markerIndex);
                if ~isempty(marker) && isvalid(marker)
                    marker.Position = [markerXPositions(markerIndex), 0, markerWidth, trackHeight];
                end
            end
        end

        %-----------------------------------------------------------------%
        function updateDownloadAvatar(obj)
            activeCount = 0;
            receivedBytes = 0;
            totalBytes = 0;
            transferRate = 0;

            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if isempty(task) || ~isfield(task, 'Snapshot') || ...
                        isempty(fieldnames(task.Snapshot)) || ...
                        ~strcmp(task.Snapshot.LifecycleState, 'active')
                    continue
                end
                snapshot = task.Snapshot;
                activeCount = activeCount + 1;
                if isfinite(snapshot.ReceivedBytes)
                    receivedBytes = receivedBytes + max(0, double(snapshot.ReceivedBytes));
                end
                if ~isempty(snapshot.TotalBytes) && isfinite(snapshot.TotalBytes) && snapshot.TotalBytes > 0
                    totalBytes = totalBytes + double(snapshot.TotalBytes);
                end
                if isfinite(snapshot.TransferRate) && snapshot.TransferRate > 0
                    transferRate = transferRate + double(snapshot.TransferRate);
                end
            end

            percentage = 0;
            if totalBytes > 0
                percentage = min(100, receivedBytes / totalBytes * 100);
            end
            state = struct('level', avatarLevel(percentage), ...
                           'inProgress', activeCount > 0, ...
                           'ballCount', activeCount, ...
                           'speedRadiansPerSecond', transferRate / 1024^2 * 2 * pi);
            if isequal(state, obj.AvatarState)
                return
            end
            obj.AvatarState = state;
            if obj.AvatarHTMLReady && ~isempty(obj.AvatarHTML) && isvalid(obj.AvatarHTML)
                obj.AvatarHTML.Data = state;
            end
        end
    end


    methods (Access = private)
        %-----------------------------------------------------------------%
        function [finalPath, cancelled, allowSourceFilename] = resolveFinalPath(obj, url)
            cancelled = false;
            [fileName, isUsefulURLName] = obj.resolveDownloadFileName(url);
            allowSourceFilename = ~isUsefulURLName;
            if strcmp(obj.executionMode, 'webApp')
                if isempty(strtrim(obj.TargetPath)) || ~isfolder(obj.TargetPath)
                    error('ui:DownloadPanel:missingTargetPath', ...
                          'TargetPath must be an existing folder in webApp mode.')
                end
                finalPath = fullfile(obj.TargetPath, fileName);
                return
            end

            defaultName = fileName;
            if ~isempty(strtrim(obj.TargetPath))
                defaultName = fullfile(obj.TargetPath, fileName);
            end
            if isempty(obj.DestinationResolver)
                [selectedName, selectedFolder] = uiputfile('*.*', '', defaultName);
                resolution = struct('Cancelled', isequal(selectedName, 0), ...
                                    'TargetFolder', selectedFolder, ...
                                    'FileName', selectedName);
            else
                context = struct('ExecutionMode', obj.executionMode, ...
                                 'URL', url, ...
                                 'SuggestedFileName', fileName, ...
                                 'InitialFolder', obj.TargetPath, ...
                                 'UIFigure', obj.UIFigure);
                resolution = obj.DestinationResolver(context);
            end
            resolution = normalizeDestinationResolution(resolution);
            if resolution.Cancelled
                finalPath = '';
                cancelled = true;
                allowSourceFilename = false;
                return
            end
            resolution.FileName = appendSourceExtension(resolution.FileName, ...
                                                         fileName, isUsefulURLName);
            if isempty(obj.DestinationResolver)
                figure(obj.UIFigure)
            end
            finalPath = fullfile(resolution.TargetFolder, resolution.FileName);
            allowSourceFilename = false;
        end

        %-----------------------------------------------------------------%
        function [fileName, isUseful] = resolveDownloadFileName(obj, url)
            [fileName, isUseful] = download.downloadFileName(url, shortTaskID());
            if isUseful
                return
            end

            matchingURL = strcmp(obj.DownloadFileNames(:, 1), url);
            matchingIndex = find(matchingURL, 1, 'last');
            if ~isempty(matchingIndex)
                fileName = obj.DownloadFileNames{matchingIndex, 2};
                return
            end

            obj.DownloadFileNames(end+1, :) = {url, fileName};
        end
    end


    % Static helpers used for validation and execution-mode-independent paths.
    methods (Static, Access = private)
        %-----------------------------------------------------------------%
        function setExecutionModeValue(obj, value)
            obj.executionMode = value;
        end
    end


    % Public property validation.
    methods
        %-----------------------------------------------------------------%
        function set.executionMode(obj, value)
            % SET.EXECUTIONMODE Validate and assign the execution mode.
            value = char(value);
            allowedValues = {'webApp', 'desktopStandaloneApp', 'MATLABEnvironment'};
            if ~ismember(value, allowedValues)
                error('ui:DownloadPanel:invalidExecutionMode', ...
                      'executionMode must be webApp, desktopStandaloneApp, or MATLABEnvironment.')
            end
            obj.executionMode = value;
        end

        %-----------------------------------------------------------------%
        function set.CollisionPolicy(obj, value)
            % SET.COLLISIONPOLICY Validate the target-conflict policy.
            value = char(value);
            allowedValues = {'askInRow', 'overwrite', 'uniqueName', 'reject'};
            if ~ismember(value, allowedValues)
                error('ui:DownloadPanel:invalidCollisionPolicy', ...
                      'CollisionPolicy is not supported.')
            end
            obj.CollisionPolicy = value;
        end

        %-----------------------------------------------------------------%
        function set.PartialConflictPolicy(obj, value)
            % SET.PARTIALCONFLICTPOLICY Validate the partial-file policy.
            value = char(value);
            allowedValues = {'askInRow', 'resume', 'restart', 'cancel'};
            if ~ismember(value, allowedValues)
                error('ui:DownloadPanel:invalidPartialConflictPolicy', ...
                      'PartialConflictPolicy is not supported.')
            end
            obj.PartialConflictPolicy = value;
        end
    end
end

%-----------------------------------------------------------------%
function figureHandle = findFigure(parentContainer)
if isa(parentContainer, 'matlab.ui.Figure')
    figureHandle = parentContainer;
else
    figureHandle = ancestor(parentContainer, 'figure');
end
end

%-----------------------------------------------------------------%
function sourcePath = avatarHTMLPath()
sourcePath = fullfile(fileparts(mfilename('fullpath')), 'html', 'downloadAvatar.html');
end

%-----------------------------------------------------------------%
function sourcePath = closeIconPath()
sourcePath = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                     'icons', 'close-16px-red.svg');
end

%-----------------------------------------------------------------%
function value = eventProperty(event, propertyNames)
value = '';
for propertyIndex = 1:numel(propertyNames)
    if isprop(event, propertyNames{propertyIndex})
        propertyValue = event.(propertyNames{propertyIndex});
        if ischar(propertyValue) || (isstring(propertyValue) && isscalar(propertyValue))
            value = char(propertyValue);
        else
            value = propertyValue;
        end
        return
    end
end
end

%-----------------------------------------------------------------%
function value = shortTaskID()
value = char(matlab.lang.internal.uuid());
value = regexprep(value, '-', '');
value = value(1:min(8, numel(value)));
end

%-----------------------------------------------------------------%
function resolution = normalizeDestinationResolution(resolution)
if ~isstruct(resolution) || ~isscalar(resolution)
    error('ui:DownloadPanel:invalidDestinationResolution', ...
          'DestinationResolver must return a scalar struct.')
end
if ~isfield(resolution, 'Cancelled') || isempty(resolution.Cancelled)
    resolution.Cancelled = false;
end
if ~isscalar(resolution.Cancelled) || ...
        ~(islogical(resolution.Cancelled) || isnumeric(resolution.Cancelled))
    error('ui:DownloadPanel:invalidDestinationResolution', ...
          'DestinationResolver Cancelled must be a logical scalar.')
end
resolution.Cancelled = logical(resolution.Cancelled);
if resolution.Cancelled
    resolution.TargetFolder = '';
    resolution.FileName = '';
    return
end
requiredFields = {'TargetFolder', 'FileName'};
for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields{fieldIndex};
    if ~isfield(resolution, fieldName) || ...
            ~(ischar(resolution.(fieldName)) || isStringScalar(resolution.(fieldName))) || ...
            isempty(strtrim(char(resolution.(fieldName))))
        error('ui:DownloadPanel:invalidDestinationResolution', ...
              'DestinationResolver must return a nonempty %s.', fieldName)
    end
    resolution.(fieldName) = char(resolution.(fieldName));
end
if ~isfolder(resolution.TargetFolder)
    error('ui:DownloadPanel:invalidDestinationResolution', ...
          'DestinationResolver TargetFolder must be an existing folder.')
end
if ~strcmp(resolution.FileName, download.downloadFileName(resolution.FileName, 'download')) || ...
        contains(resolution.FileName, {'/', '\\'})
    error('ui:DownloadPanel:invalidDestinationResolution', ...
          'DestinationResolver FileName must be a valid file name without a folder path.')
end
end

%-----------------------------------------------------------------%
function fileName = appendSourceExtension(fileName, sourceFileName, isUsefulSourceName)
if ~isUsefulSourceName
    return
end
[~, ~, selectedExtension] = fileparts(fileName);
if ~isempty(selectedExtension)
    return
end
[~, ~, sourceExtension] = fileparts(sourceFileName);
if ~isempty(sourceExtension)
    fileName = [fileName, sourceExtension];
end
end

%-----------------------------------------------------------------%
%-----------------------------------------------------------------%
function value = snapshotElapsedSeconds(snapshot)
if isempty(snapshot.StartedAt) || isempty(snapshot.UpdatedAt)
    value = 0;
    return
end
value = max(0, seconds(snapshot.UpdatedAt - snapshot.StartedAt));
end

%-----------------------------------------------------------------%
function text = progressText(receivedBytes, totalBytes, elapsedSeconds, transferRate)
receivedText = formatBytes(receivedBytes);
totalText = '-';
totalSizeText = '-';
if ~isempty(totalBytes) && totalBytes > 0
    totalText = formatBytes(totalBytes);
    totalSizeText = formatTotalBytes(totalBytes);
end
if elapsedSeconds < 10
    elapsedText = '- s';
    remainingText = '- s';
else
    elapsedText = formatDuration(elapsedSeconds);
    remainingText = '- s';
    if ~isempty(totalBytes) && totalBytes > 0 && isfinite(transferRate) && transferRate > 0
        remainingText = formatDuration(max(0, double(totalBytes) - double(receivedBytes)) / transferRate);
    end
end
text = sprintf('%s / %s (%s) | Elapsed: %s | Remaining: %s', ...
               receivedText, totalText, totalSizeText, elapsedText, remainingText);
end

%-----------------------------------------------------------------%
function text = formatBytes(value)
if isempty(value) || ~isscalar(value) || ~isfinite(value)
    text = 'unknown';
    return
end
value = double(value);
digits = sprintf('%.0f', max(0, value));
firstGroupLength = mod(numel(digits), 3);
if firstGroupLength == 0
    firstGroupLength = 3;
end
groupCount = 1 + floor((numel(digits) - firstGroupLength) / 3);
groups = cell(1, groupCount);
groups{1} = digits(1:firstGroupLength);
for groupIndex = 2:groupCount
    startIndex = firstGroupLength + (groupIndex - 2) * 3 + 1;
    groups{groupIndex} = digits(startIndex:startIndex + 2);
end
text = strjoin(groups, ' ');
end

%-----------------------------------------------------------------%
function text = formatTotalBytes(value)
value = double(value);
scales = [1024^3, 1024^2, 1024];
names = {'GBytes', 'MBytes', 'kBytes'};
unitIndex = find(value >= scales, 1, 'first');
if isempty(unitIndex)
    unitIndex = numel(scales);
end
text = sprintf('%.0f %s', max(1, round(value / scales(unitIndex))), names{unitIndex});
end

%-----------------------------------------------------------------%
function text = formatDuration(seconds)
seconds = max(0, round(double(seconds)));
if seconds < 60
    text = sprintf('%.0f s', seconds);
    return
end
minutes = floor(seconds / 60);
remainingSeconds = mod(seconds, 60);
if minutes < 60
    if remainingSeconds == 0
        text = sprintf('%.0f min', minutes);
    else
        text = sprintf('%.0f min %.0f s', minutes, remainingSeconds);
    end
    return
end
hours = floor(minutes / 60);
remainingMinutes = mod(minutes, 60);
if remainingMinutes == 0
    text = sprintf('%.0f h', hours);
else
    text = sprintf('%.0f h %.0f min', hours, remainingMinutes);
end
end

%-----------------------------------------------------------------%
function level = avatarLevel(percentage)
if percentage <= 0
    level = 0;
elseif percentage >= 90
    level = 10;
else
    level = ceil(percentage / 10);
end
end

%-----------------------------------------------------------------%
function invokeCallback(callback, varargin)
if isempty(callback)
    return
end
try
    callback(varargin{:})
catch
end
end

%-----------------------------------------------------------------%
function value = ternary(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end
