classdef DownloadPanel < handle

    % DOWNLOADPANEL Reusable asynchronous download queue UI.
    %
    % DownloadPanel owns the presentation and lifecycle of multiple download
    % rows: the download avatar, the popup panel, progress aggregation,
    % pause/resume/stop controls, conflict decisions, and cleanup of UI and
    % downloader handles. It deliberately does not know how authentication
    % or network transfer is implemented.
    %
    % The caller supplies DownloaderFactory. The factory receives a normalized
    % request containing the URL, temporary and target folders, file name,
    % task-scoped staging paths, and conflict actions. It must return an
    % object exposing start, pause, resume, stop, ProgressFcn, CompletedFcn,
    % and ErrorFcn.
    %
    % Temporary files are written below TempPath. Completed files are written
    % below TargetPath. Existing target and partial-file conflicts are shown
    % in the download row instead of being handled by modal dialogs.

    properties
        executionMode (1,:) char = 'MATLABEnvironment'
        TempPath (1,:) char = ''
        TargetPath (1,:) char = ''
        CollisionPolicy (1,:) char = 'askInRow'
        PartialConflictPolicy (1,:) char = 'askInRow'
        CompletedFcn = []
        ErrorFcn = []
    end

    properties (SetAccess = private)
        AvatarHTML
        DownloaderFactory
    end

    properties (Access = private)
        ParentContainer
        UIFigure
        DownloadDialog
        DownloadHeader
        DownloadTitleLabel
        CloseImage
        DownloadContent
        DownloadStack
        DownloadTasks = {}
        NextDownloadID (1,1) double = 0
        AvatarHTMLReady (1,1) logical = false
        AvatarState struct = struct('level', 0, ...
                                    'inProgress', false, ...
                                    'ballCount', 0, ...
                                    'speedRadiansPerSecond', 0)
        OriginalWindowButtonDownFcn = []
        IsDeleting (1,1) logical = false
    end


    methods
        %-----------------------------------------------------------------%
        function obj = DownloadPanel(parentContainer, options)
            % DOWNLOADPANEL Construct a download panel attached to a UI parent.
            %
            % PARENTCONTAINER is a UI container belonging to a figure.
            % DOWNLOADERFACTORY is a function handle that creates one
            % downloader object from the normalized request generated by the
            % panel. Optional name-value arguments configure execution mode,
            % temporary and target folders, and conflict policies.
            arguments
                parentContainer
                options.DownloaderFactory (1,1) function_handle
                options.executionMode (1,:) char = 'MATLABEnvironment'
                options.tempPath (1,:) char = tempdir
                options.targetPath (1,:) char = ''
                options.CollisionPolicy (1,:) char = 'askInRow'
                options.PartialConflictPolicy (1,:) char = 'askInRow'
            end

            obj.ParentContainer = parentContainer;
            obj.UIFigure = findFigure(parentContainer);
            if isempty(obj.UIFigure) || ~isvalid(obj.UIFigure)
                error('ui:DownloadPanel:invalidParent', ...
                      'The parent container must belong to a valid figure.')
            end

            obj.DownloaderFactory = options.DownloaderFactory;
            obj.executionMode = options.executionMode;
            obj.TempPath = char(options.tempPath);
            obj.TargetPath = char(options.targetPath);
            obj.CollisionPolicy = options.CollisionPolicy;
            obj.PartialConflictPolicy = options.PartialConflictPolicy;

            obj.AvatarHTML = uihtml(parentContainer);
            obj.AvatarHTML.HTMLSource = avatarHTMLPath();
            obj.AvatarHTML.HTMLEventReceivedFcn = @(~, event) obj.onAvatarEvent(event);

            obj.OriginalWindowButtonDownFcn = obj.UIFigure.WindowButtonDownFcn;
            obj.UIFigure.WindowButtonDownFcn = @(source, event) obj.onFigureButtonDown(source, event);
        end

        %-----------------------------------------------------------------%
        function delete(obj)
            % DELETE Stop active downloads and release panel-owned UI handles.
            if obj.IsDeleting
                return
            end
            obj.IsDeleting = true;

            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if isempty(task)
                    continue
                end
                obj.stopAndReleaseDownloader(task)
                obj.deleteTaskGraphics(task)
            end
            obj.DownloadTasks = {};
            obj.closeDownloadContainer()

            if ~isempty(obj.AvatarHTML) && isvalid(obj.AvatarHTML)
                delete(obj.AvatarHTML)
            end
            if ~isempty(obj.UIFigure) && isvalid(obj.UIFigure)
                obj.UIFigure.WindowButtonDownFcn = obj.OriginalWindowButtonDownFcn;
            end
        end

        %-----------------------------------------------------------------%
        function taskID = addDownload(obj, url)
            % ADDDOWNLOAD Add and start a download for a URL.
            %
            % The file name is derived from URL. Depending on executionMode,
            % the target is resolved directly or through a file-selection
            % dialog. The method returns the numeric task identifier, or an
            % empty value when the user cancels destination selection.
            arguments
                obj
                url (1,:) char {mustBeNonempty}
            end

            url = char(url);
            [finalPath, cancelled] = obj.resolveFinalPath(url);
            if cancelled
                taskID = [];
                return
            end

            [targetFolder, fileName, extension] = fileparts(finalPath);
            fileName = [fileName, extension];
            taskID = obj.createTask(url, targetFolder, fileName, finalPath);
            task = obj.getTask(taskID);
            existingPartialPath = findPartialPath(task.TempFolder, task.FileName);
            if ~isempty(existingPartialPath)
                task.PartialPath = existingPartialPath;
                task.ChunkPath = [existingPartialPath, '.chunk'];
            end
            obj.DownloadTasks{taskID} = task;

            if pathExists(finalPath)
                obj.configureTargetConflict(taskID)
            elseif ~isempty(existingPartialPath)
                obj.configurePartialConflict(taskID)
            else
                obj.startTask(taskID, 'none', 'none')
            end
        end

        %-----------------------------------------------------------------%
        function show(obj)
            % SHOW Make the download popup visible and bring it to the front.
            if isempty(obj.DownloadDialog) || ~isvalid(obj.DownloadDialog)
                return
            end
            obj.DownloadDialog.Visible = 'on';
            drawnow
            obj.positionDownloadContainer()
            uistack(obj.DownloadDialog, 'top')
        end

        %-----------------------------------------------------------------%
        function hide(obj)
            % HIDE Hide the download popup without stopping its downloads.
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog)
                obj.DownloadDialog.Visible = 'off';
            end
        end

        %-----------------------------------------------------------------%
        function stop(obj, taskID)
            % STOP Stop and remove one download task.
            %
            % The task's partial and chunk files are retained so a later
            % addDownload call can offer resume or restart.
            task = obj.getTask(taskID);
            if isempty(task)
                return
            end

            task.IsStopped = true;
            task.LifecycleState = 'stopped';
            obj.DownloadTasks{taskID} = task;
            obj.stopAndReleaseDownloader(task)
            restoreBackup(task)
            obj.removeTask(taskID)
        end

        %-----------------------------------------------------------------%
        function stopAll(obj)
            % STOPALL Stop and remove every download task in the panel.
            for taskID = 1:numel(obj.DownloadTasks)
                if ~isempty(obj.DownloadTasks{taskID})
                    obj.stop(taskID)
                end
            end
        end

        %-----------------------------------------------------------------%
        function tf = isActive(obj, filePath)
            % ISACTIVE Return true when a task targets filePath.
            tf = false;
            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if isempty(task) || task.IsStopped
                    continue
                end
                if strcmpi(task.FinalPath, filePath)
                    tf = true;
                    return
                end
            end
        end
    end


    % Private implementation: HTML events, task state, row controls, layout,
    % conflict handling, and aggregate avatar updates.
    methods (Access = private)
        %-----------------------------------------------------------------%
        function onAvatarEvent(obj, event)
            eventName = eventProperty(event, {'HTMLEventName', 'EventName'});
            payload = eventProperty(event, {'HTMLEventData', 'Data'});
            if ischar(payload) || (isstring(payload) && isscalar(payload))
                try
                    payload = jsondecode(char(payload));
                catch
                    payload = struct();
                end
            end

            if strcmp(eventName, 'downloadAvatarReady') || ...
                    (isstruct(payload) && isfield(payload, 'type') && strcmp(string(payload.type), 'ready'))
                obj.AvatarHTMLReady = true;
                obj.AvatarHTML.Data = obj.AvatarState;
                return
            end

            if strcmp(eventName, 'downloadAvatarClick') || ...
                    (isstruct(payload) && isfield(payload, 'type') && strcmp(string(payload.type), 'click'))
                obj.show()
            end
        end

        %-----------------------------------------------------------------%
        function onFigureButtonDown(obj, source, event)
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog) && ...
                    strcmp(obj.DownloadDialog.Visible, 'on')
                point = obj.UIFigure.CurrentPoint;
                panelPosition = obj.DownloadDialog.Position;
                insidePanel = point(1) >= panelPosition(1) && ...
                              point(1) <= panelPosition(1) + panelPosition(3) && ...
                              point(2) >= panelPosition(2) && ...
                              point(2) <= panelPosition(2) + panelPosition(4);
                if ~insidePanel
                    obj.hide()
                end
            end
            invokeCallback(obj.OriginalWindowButtonDownFcn, source, event)
        end

        %-----------------------------------------------------------------%
        function taskID = createTask(obj, url, targetFolder, fileName, finalPath)
            obj.NextDownloadID = obj.NextDownloadID + 1;
            taskID = obj.NextDownloadID;
            task = obj.createTaskGraphics(taskID, fileName);
            task.ID = taskID;
            task.TaskID = shortTaskID();
            task.URL = url;
            task.FileName = fileName;
            task.TempFolder = obj.TempPath;
            task.TargetFolder = targetFolder;
            task.FinalPath = finalPath;
            task.PartialPath = fullfile(obj.TempPath, [task.TaskID, '_', fileName, '.part']);
            task.ChunkPath = [task.PartialPath, '.chunk'];
            task.BackupPath = '';
            task.ConflictType = '';
            task.CollisionAction = 'none';
            task.PartialAction = 'none';
            task.Downloader = [];
            task.Request = struct();
            task.LifecycleState = 'created';
            task.IsPaused = false;
            task.IsStopped = false;
            task.ReceivedBytes = 0;
            task.TotalBytes = [];
            task.ProgressFraction = 0;
            task.TransferRate = NaN;
            task.StartTimer = tic;
            task.ProgressSamples = zeros(0, 2);
            obj.DownloadTasks{taskID} = task;
            obj.refreshDownloadContainer()
        end

        %-----------------------------------------------------------------%
        function task = createTaskGraphics(obj, taskID, fileName)
            obj.ensureDownloadContainer()

            task = struct('ID', taskID, ...
                          'TaskID', '', ...
                          'URL', '', ...
                          'FileName', fileName, ...
                          'TempFolder', '', ...
                          'TargetFolder', '', ...
                          'FinalPath', '', ...
                          'PartialPath', '', ...
                          'ChunkPath', '', ...
                          'BackupPath', '', ...
                          'Downloader', [], ...
                          'Request', struct(), ...
                          'LifecycleState', 'created', ...
                          'ConflictType', '', ...
                          'CollisionAction', 'none', ...
                          'PartialAction', 'none', ...
                          'IsPaused', false, ...
                          'IsStopped', false, ...
                          'ReceivedBytes', 0, ...
                          'TotalBytes', [], ...
                          'ProgressFraction', 0, ...
                          'TransferRate', NaN, ...
                          'StartTimer', [], ...
                          'ProgressSamples', zeros(0, 2), ...
                          'Dialog', [], ...
                          'Separator', [], ...
                          'GridLayout', [], ...
                          'StatusLabel', [], ...
                          'BytesLabel', [], ...
                          'ProgressTrack', [], ...
                          'ProgressFill', [], ...
                          'ProgressMarkers', [], ...
                          'PauseButton', [], ...
                          'StopButton', [], ...
                          'ConflictPanel', [], ...
                          'ConflictButtons', [], ...
                          'RowHeight', 154);

            task.Dialog = uipanel(obj.DownloadStack, ...
                                  'BorderType', 'none', ...
                                  'BackgroundColor', obj.UIFigure.Color);
            task.Separator = uipanel(obj.DownloadStack, ...
                                     'BorderType', 'none', ...
                                     'BackgroundColor', [0.55, 0.55, 0.55], ...
                                     'Visible', 'off');
            task.GridLayout = uigridlayout(task.Dialog, [5, 3]);
            task.GridLayout.Padding = [16, 12, 16, 8];
            task.GridLayout.RowSpacing = 4;
            task.GridLayout.RowHeight = {24, 20, 46, 30, 1};
            task.GridLayout.ColumnWidth = {'1x', 90, 90};

            task.StatusLabel = uilabel(task.GridLayout, ...
                                       'Text', fileName, ...
                                       'HorizontalAlignment', 'left', ...
                                       'VerticalAlignment', 'bottom', ...
                                       'WordWrap', 'on');
            task.StatusLabel.Layout.Row = 1;
            task.StatusLabel.Layout.Column = [1, 3];

            task.ProgressTrack = uipanel(task.GridLayout, ...
                                         'BorderType', 'none', ...
                                         'BackgroundColor', obj.UIFigure.Color);
            task.ProgressTrack.Layout.Row = 2;
            task.ProgressTrack.Layout.Column = [1, 3];

            task.ProgressFill = uipanel(task.ProgressTrack, ...
                                        'BorderType', 'none', ...
                                        'BackgroundColor', [0, 0.447, 0.741], ...
                                        'Units', 'pixels', ...
                                        'Position', [0, 0, 0, 1]);
            task.ProgressMarkers = gobjects(1, 5);
            for markerIndex = 1:numel(task.ProgressMarkers)
                task.ProgressMarkers(markerIndex) = uipanel(task.ProgressTrack, ...
                                                             'BorderType', 'none', ...
                                                             'BackgroundColor', [0.45, 0.45, 0.45], ...
                                                             'Units', 'pixels', ...
                                                             'Position', [0, 0, 1, 1]);
            end

            task.BytesLabel = uilabel(task.GridLayout, 'Text', '', 'WordWrap', 'on');
            task.BytesLabel.Layout.Row = 3;
            task.BytesLabel.Layout.Column = [1, 3];

            task.PauseButton = uibutton(task.GridLayout, ...
                                        'Text', 'Pause', ...
                                        'ButtonPushedFcn', @(~, ~) obj.togglePause(taskID));
            task.PauseButton.Layout.Row = 4;
            task.PauseButton.Layout.Column = 2;

            task.StopButton = uibutton(task.GridLayout, ...
                                       'Text', 'Stop', ...
                                       'ButtonPushedFcn', @(~, ~) obj.stop(taskID));
            task.StopButton.Layout.Row = 4;
            task.StopButton.Layout.Column = 3;

            task.ConflictPanel = uipanel(task.GridLayout, ...
                                         'BorderType', 'none', ...
                                         'Visible', 'off');
            task.ConflictPanel.Layout.Row = 5;
            task.ConflictPanel.Layout.Column = [1, 3];
            conflictLayout = uigridlayout(task.ConflictPanel, [1, 3]);
            conflictLayout.Padding = [0, 0, 0, 0];
            conflictLayout.ColumnWidth = {'1x', '1x', '1x'};
            task.ConflictButtons = gobjects(1, 3);
            task.ConflictButtons(1) = uibutton(conflictLayout, ...
                                               'Text', 'Overwrite', ...
                                               'ButtonPushedFcn', @(~, ~) obj.resolveConflict(taskID, 'overwrite'));
            task.ConflictButtons(2) = uibutton(conflictLayout, ...
                                               'Text', 'Save as new', ...
                                               'ButtonPushedFcn', @(~, ~) obj.resolveConflict(taskID, 'uniqueName'));
            task.ConflictButtons(3) = uibutton(conflictLayout, ...
                                               'Text', 'Cancel', ...
                                               'ButtonPushedFcn', @(~, ~) obj.resolveConflict(taskID, 'cancel'));
            drawnow
            obj.updateProgressScale(task)
        end

        %-----------------------------------------------------------------%
        function configureTargetConflict(obj, taskID)
            task = obj.getTask(taskID);
            if isempty(task)
                return
            end
            task.ConflictType = 'target';
            obj.DownloadTasks{taskID} = task;
            if strcmp(obj.CollisionPolicy, 'overwrite')
                obj.resolveConflict(taskID, 'overwrite')
                return
            elseif strcmp(obj.CollisionPolicy, 'uniqueName')
                obj.resolveConflict(taskID, 'uniqueName')
                return
            elseif strcmp(obj.CollisionPolicy, 'reject')
                obj.resolveConflict(taskID, 'cancel')
                return
            end

            task.ConflictType = 'target';
            task.LifecycleState = 'awaitingConflictDecision';
            task.StatusLabel.Text = sprintf('%s already exists', task.FileName);
            task.BytesLabel.Text = 'Choose an action to continue.';
            task.ConflictButtons(1).Text = 'Overwrite';
            task.ConflictButtons(1).ButtonPushedFcn = @(~, ~) obj.resolveConflict(taskID, 'overwrite');
            task.ConflictButtons(2).Text = 'Save as new';
            task.ConflictButtons(2).ButtonPushedFcn = @(~, ~) obj.resolveConflict(taskID, 'uniqueName');
            task.ConflictButtons(3).Text = 'Cancel';
            task.ConflictButtons(3).ButtonPushedFcn = @(~, ~) obj.resolveConflict(taskID, 'cancel');
            for buttonIndex = 1:numel(task.ConflictButtons)
                task.ConflictButtons(buttonIndex).Enable = 'on';
            end
            task.ConflictPanel.Visible = 'on';
            task.PauseButton.Visible = 'off';
            task.StopButton.Visible = 'off';
            task.GridLayout.RowHeight = {24, 20, 46, 30, 30};
            task.RowHeight = 190;
            obj.DownloadTasks{taskID} = task;
            obj.refreshDownloadContainer()
            obj.show()
            obj.updateDownloadAvatar()
        end

        %-----------------------------------------------------------------%
        function configurePartialConflict(obj, taskID)
            task = obj.getTask(taskID);
            if isempty(task)
                return
            end
            task.ConflictType = 'partial';
            obj.DownloadTasks{taskID} = task;
            if strcmp(obj.PartialConflictPolicy, 'resume')
                obj.resolveConflict(taskID, 'resume')
                return
            elseif strcmp(obj.PartialConflictPolicy, 'restart')
                obj.resolveConflict(taskID, 'restart')
                return
            elseif strcmp(obj.PartialConflictPolicy, 'cancel')
                obj.resolveConflict(taskID, 'cancel')
                return
            end

            task.LifecycleState = 'awaitingConflictDecision';
            task.StatusLabel.Text = sprintf('Partial download found for %s', task.FileName);
            task.BytesLabel.Text = 'Resume, restart, or cancel this download.';
            task.ConflictButtons(1).Text = 'Resume';
            task.ConflictButtons(1).ButtonPushedFcn = @(~, ~) obj.resolveConflict(taskID, 'resume');
            task.ConflictButtons(2).Text = 'Restart';
            task.ConflictButtons(2).ButtonPushedFcn = @(~, ~) obj.resolveConflict(taskID, 'restart');
            task.ConflictButtons(3).Text = 'Cancel';
            task.ConflictButtons(3).ButtonPushedFcn = @(~, ~) obj.resolveConflict(taskID, 'cancel');
            for buttonIndex = 1:numel(task.ConflictButtons)
                task.ConflictButtons(buttonIndex).Enable = 'on';
            end
            task.ConflictPanel.Visible = 'on';
            task.PauseButton.Visible = 'off';
            task.StopButton.Visible = 'off';
            task.GridLayout.RowHeight = {24, 20, 46, 30, 30};
            task.RowHeight = 190;
            obj.DownloadTasks{taskID} = task;
            obj.refreshDownloadContainer()
            obj.show()
            obj.updateDownloadAvatar()
        end

        %-----------------------------------------------------------------%
        function resolveConflict(obj, taskID, action)
            task = obj.getTask(taskID);
            if isempty(task) || ~strcmp(task.LifecycleState, 'awaitingConflictDecision')
                return
            end
            wasTargetConflict = strcmp(task.ConflictType, 'target');

            if strcmp(action, 'cancel')
                obj.stop(taskID)
                return
            end

            if strcmp(task.ConflictType, 'target') && strcmp(action, 'overwrite')
                task.BackupPath = fullfile(task.TempFolder, [task.TaskID, '_backup_', task.FileName]);
                try
                    ensureFolder(task.TempFolder)
                    moveFileWithFallback(task.FinalPath, task.BackupPath)
                catch exception
                    obj.onDownloadError(taskID, exception)
                    return
                end
                task.CollisionAction = 'overwrite';
            elseif strcmp(task.ConflictType, 'target') && strcmp(action, 'uniqueName')
                task.FinalPath = uniqueTargetPath(task.FinalPath);
                [task.TargetFolder, baseName, extension] = fileparts(task.FinalPath);
                task.FileName = [baseName, extension];
                task.StatusLabel.Text = task.FileName;
                task.PartialPath = fullfile(task.TempFolder, [task.TaskID, '_', task.FileName, '.part']);
                task.ChunkPath = [task.PartialPath, '.chunk'];
                task.CollisionAction = 'uniqueName';
            elseif strcmp(task.ConflictType, 'partial') && strcmp(action, 'restart')
                deleteIfExists(task.PartialPath)
                deleteIfExists(task.ChunkPath)
                task.PartialPath = fullfile(task.TempFolder, [task.TaskID, '_', task.FileName, '.part']);
                task.ChunkPath = [task.PartialPath, '.chunk'];
                task.PartialAction = 'restart';
            elseif strcmp(task.ConflictType, 'partial') && strcmp(action, 'resume')
                task.PartialAction = 'resume';
            end

            for buttonIndex = 1:numel(task.ConflictButtons)
                task.ConflictButtons(buttonIndex).Enable = 'off';
            end
            task.ConflictPanel.Visible = 'off';
            task.PauseButton.Visible = 'on';
            task.StopButton.Visible = 'on';
            task.GridLayout.RowHeight = {24, 20, 46, 30, 1};
            task.RowHeight = 154;
            task.ConflictType = '';
            obj.DownloadTasks{taskID} = task;
            obj.refreshDownloadContainer()
            if wasTargetConflict && ~isempty(task.PartialPath) && isfile(task.PartialPath)
                obj.configurePartialConflict(taskID)
                return
            end
            obj.startTask(taskID, task.CollisionAction, task.PartialAction)
        end

        %-----------------------------------------------------------------%
        function startTask(obj, taskID, collisionAction, partialAction)
            task = obj.getTask(taskID);
            if isempty(task) || task.IsStopped
                return
            end

            try
                ensureFolder(task.TempFolder)
                task.Request = struct('URL', task.URL, ...
                                      'TaskID', task.TaskID, ...
                                      'TempFolder', task.TempFolder, ...
                                      'TargetFolder', task.TargetFolder, ...
                                      'FileName', task.FileName, ...
                                      'FinalPath', task.FinalPath, ...
                                      'PartialPath', task.PartialPath, ...
                                      'ChunkPath', task.ChunkPath, ...
                                      'BackupPath', task.BackupPath, ...
                                      'CollisionAction', collisionAction, ...
                                      'PartialAction', partialAction);
                downloader = obj.DownloaderFactory(task.Request);
                validateDownloader(downloader)
                task.Downloader = downloader;
                task.LifecycleState = 'active';
                task.IsPaused = false;
                obj.DownloadTasks{taskID} = task;

                downloader.ProgressFcn = @(receivedBytes, totalBytes) obj.onDownloadProgress(taskID, receivedBytes, totalBytes);
                downloader.CompletedFcn = @(info) obj.onDownloadCompleted(taskID, info);
                downloader.ErrorFcn = @(exception) obj.onDownloadError(taskID, exception);
                obj.refreshDownloadContainer()
                obj.updateDownloadAvatar()
                start(downloader)
            catch exception
                obj.onDownloadError(taskID, exception)
            end
        end

        %-----------------------------------------------------------------%
        function togglePause(obj, taskID)
            task = obj.getTask(taskID);
            if isempty(task) || ~ismember(task.LifecycleState, {'active', 'paused'}) || ...
                    isempty(task.Downloader)
                return
            end

            if task.IsPaused
                resume(task.Downloader)
                task.IsPaused = false;
                task.LifecycleState = 'active';
                task.PauseButton.Text = 'Pause';
            else
                pause(task.Downloader)
                task.IsPaused = true;
                task.LifecycleState = 'paused';
                task.PauseButton.Text = 'Resume';
            end
            task.TransferRate = NaN;
            obj.DownloadTasks{taskID} = task;
            obj.updateDownloadAvatar()
        end

        %-----------------------------------------------------------------%
        function onDownloadProgress(obj, taskID, receivedBytes, totalBytes)
            task = obj.getTask(taskID);
            if isempty(task) || ~strcmp(task.LifecycleState, 'active') || obj.IsDeleting
                return
            end

            receivedBytes = double(receivedBytes);
            if isempty(totalBytes)
                totalBytes = [];
            else
                totalBytes = double(totalBytes);
            end
            task.ReceivedBytes = receivedBytes;
            task.TotalBytes = totalBytes;

            elapsedSeconds = toc(task.StartTimer);
            task.ProgressSamples(end+1, :) = [elapsedSeconds, receivedBytes];
            cutoffTime = elapsedSeconds - 10;
            samplesBeforeCutoff = find(task.ProgressSamples(:, 1) <= cutoffTime, 1, 'last');
            if ~isempty(samplesBeforeCutoff)
                task.ProgressSamples = task.ProgressSamples(samplesBeforeCutoff:end, :);
            end

            transferRate = 100000;
            if elapsedSeconds >= 10 && size(task.ProgressSamples, 1) >= 2
                sampleDuration = task.ProgressSamples(end, 1) - task.ProgressSamples(1, 1);
                if sampleDuration >= 10
                    transferRate = (task.ProgressSamples(end, 2) - task.ProgressSamples(1, 2)) / sampleDuration;
                end
            end

            if isempty(totalBytes) || totalBytes <= 0
                fraction = 0;
            else
                fraction = min(receivedBytes / totalBytes, 1);
            end
            task.ProgressFraction = fraction;
            task.TransferRate = transferRate;
            task.BytesLabel.Text = progressText(receivedBytes, totalBytes, elapsedSeconds, transferRate);
            obj.updateProgressScale(task)
            obj.DownloadTasks{taskID} = task;
            obj.updateDownloadAvatar()
            drawnow limitrate
        end

        %-----------------------------------------------------------------%
        function onDownloadCompleted(obj, taskID, info)
            task = obj.getTask(taskID);
            if isempty(task) || task.IsStopped
                return
            end

            if ~isstruct(info)
                info = struct('FinalPath', task.FinalPath, 'BytesReceived', task.ReceivedBytes, 'TotalBytes', task.TotalBytes);
            elseif ~isfield(info, 'FinalPath') || isempty(info.FinalPath)
                info.FinalPath = task.FinalPath;
            end
            taskInfo = publicTaskInfo(task);
            taskInfo.FinalPath = info.FinalPath;
            obj.removeTask(taskID)
            invokeCallback(obj.CompletedFcn, taskID, info, taskInfo)
        end

        %-----------------------------------------------------------------%
        function onDownloadError(obj, taskID, exception)
            task = obj.getTask(taskID);
            if isempty(task) || task.IsStopped
                return
            end
            taskInfo = publicTaskInfo(task);
            restoreBackup(task)
            obj.removeTask(taskID)
            invokeCallback(obj.ErrorFcn, taskID, exception, taskInfo)
        end

        %-----------------------------------------------------------------%
        function removeTask(obj, taskID)
            task = obj.getTask(taskID);
            if isempty(task)
                return
            end
            obj.stopAndReleaseDownloader(task)
            obj.deleteTaskGraphics(task)
            obj.DownloadTasks{taskID} = [];
            obj.refreshDownloadContainer()
            obj.updateDownloadAvatar()
        end

        %-----------------------------------------------------------------%
        function task = getTask(obj, taskID)
            task = [];
            if ~isscalar(taskID) || taskID < 1 || taskID > numel(obj.DownloadTasks)
                return
            end
            task = obj.DownloadTasks{taskID};
            if isempty(task)
                task = [];
            end
        end

        %-----------------------------------------------------------------%
        function stopAndReleaseDownloader(~, task)
            downloader = task.Downloader;
            if isempty(downloader)
                return
            end
            try
                if isprop(downloader, 'ProgressFcn')
                    downloader.ProgressFcn = [];
                end
                if isprop(downloader, 'CompletedFcn')
                    downloader.CompletedFcn = [];
                end
                if isprop(downloader, 'ErrorFcn')
                    downloader.ErrorFcn = [];
                end
            catch
            end
            try
                if ismethod(downloader, 'stop')
                    stop(downloader)
                end
            catch
            end
            try
                if ismethod(downloader, 'delete')
                    delete(downloader)
                end
            catch
            end
        end

        %-----------------------------------------------------------------%
        function deleteTaskGraphics(~, task)
            handles = {task.Dialog, task.Separator};
            for handleIndex = 1:numel(handles)
                handle = handles{handleIndex};
                try
                    if ~isempty(handle) && isvalid(handle)
                        delete(handle)
                    end
                catch
                end
            end
        end

        %-----------------------------------------------------------------%
        function ensureDownloadContainer(obj)
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog)
                return
            end

            obj.DownloadDialog = uipanel(obj.UIFigure, ...
                                         'Title', '', ...
                                         'Visible', 'off', ...
                                         'Scrollable', 'off', ...
                                         'Units', 'pixels', ...
                                         'BorderType', 'line', ...
                                         'BackgroundColor', obj.UIFigure.Color);
            obj.DownloadHeader = uipanel(obj.DownloadDialog, ...
                                         'BorderType', 'none', ...
                                         'BackgroundColor', obj.UIFigure.Color);
            obj.DownloadTitleLabel = uilabel(obj.DownloadHeader, ...
                                             'Text', 'Downloads', ...
                                             'FontWeight', 'bold', ...
                                             'HorizontalAlignment', 'left', ...
                                             'VerticalAlignment', 'center');
            obj.CloseImage = uiimage(obj.DownloadHeader, ...
                                     'ImageSource', closeIconPath(), ...
                                     'ImageClickedFcn', @(~, ~) obj.hide());
            obj.DownloadContent = uipanel(obj.DownloadDialog, ...
                                          'BorderType', 'none', ...
                                          'Units', 'pixels', ...
                                          'BackgroundColor', obj.UIFigure.Color);
            obj.DownloadStack = uigridlayout(obj.DownloadContent, [1, 1]);
            obj.DownloadStack.Padding = [0, 0, 0, 0];
            obj.DownloadStack.RowSpacing = 0;
            obj.DownloadStack.ColumnWidth = {'1x'};
            obj.DownloadStack.RowHeight = {154};
            obj.positionDownloadContainer()
        end

        %-----------------------------------------------------------------%
        function closeDownloadContainer(obj)
            if ~isempty(obj.DownloadDialog) && isvalid(obj.DownloadDialog)
                delete(obj.DownloadDialog)
            end
            obj.DownloadDialog = [];
            obj.DownloadContent = [];
            obj.DownloadStack = [];
        end

        %-----------------------------------------------------------------%
        function refreshDownloadContainer(obj)
            if isempty(obj.DownloadDialog) || ~isvalid(obj.DownloadDialog)
                return
            end

            activeIDs = [];
            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if ~isempty(task) && ~isempty(task.Dialog) && isvalid(task.Dialog)
                    activeIDs(end+1) = taskID;
                end
            end

            if isempty(activeIDs)
                obj.closeDownloadContainer()
                return
            end

            activeIDs = fliplr(activeIDs);
            rowHeights = repmat({1}, 1, 2*numel(activeIDs));
            for row = 1:numel(activeIDs)
                task = obj.DownloadTasks{activeIDs(row)};
                rowHeights{2*row - 1} = task.RowHeight;
                task.Dialog.Layout.Row = 2*row - 1;
                task.Dialog.Layout.Column = 1;
                task.Separator.Layout.Row = 2*row;
                task.Separator.Layout.Column = 1;
                task.Separator.Visible = ternary(row < numel(activeIDs), 'on', 'off');
            end
            obj.DownloadStack.RowHeight = rowHeights;
            obj.positionDownloadContainer()
            obj.resizeDownloadProgressBars()
        end

        %-----------------------------------------------------------------%
        function positionDownloadContainer(obj)
            if isempty(obj.DownloadDialog) || ~isvalid(obj.DownloadDialog) || ...
                    isempty(obj.AvatarHTML) || ~isvalid(obj.AvatarHTML)
                return
            end

            drawnow limitrate
            avatarPosition = getpixelposition(obj.AvatarHTML, true);
            figurePosition = obj.UIFigure.Position;
            figureWidth = figurePosition(3);
            figureHeight = figurePosition(4);
            panelWidth = min(560, max(220, figureWidth - 16));
            headerHeight = 24;
            borderInset = 2;
            panelGap = 12;
            activeHeight = 0;
            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if ~isempty(task)
                    activeHeight = activeHeight + task.RowHeight + 1;
                end
            end
            contentHeight = max(1, activeHeight);
            requiredPanelHeight = contentHeight + headerHeight + 2 * borderInset;
            availablePanelHeight = min(avatarPosition(2) - panelGap - 8, figureHeight - 16);
            panelHeight = min(max(64, requiredPanelHeight), max(64, availablePanelHeight));
            panelX = min(max(8, avatarPosition(1)), max(8, figureWidth - panelWidth - 8));
            panelY = avatarPosition(2) - panelHeight - panelGap;
            panelY = min(max(8, panelY), max(8, figureHeight - panelHeight - 8));

            obj.DownloadDialog.Position = [panelX, panelY, panelWidth, panelHeight];
            innerPosition = obj.DownloadDialog.InnerPosition;
            needsVerticalScroll = contentHeight > innerPosition(4);
            obj.DownloadDialog.Scrollable = ternary(needsVerticalScroll, 'on', 'off');
            drawnow limitrate
            innerPosition = obj.DownloadDialog.InnerPosition;
            contentWidth = max(1, floor(innerPosition(3)) - 16 - 2 * borderInset);
            obj.DownloadContent.Position = [borderInset, borderInset, contentWidth, contentHeight];
            obj.DownloadHeader.Position = [borderInset, contentHeight + borderInset, contentWidth, headerHeight];
            obj.DownloadTitleLabel.Position = [8, 0, max(1, contentWidth - 32), headerHeight];
            closeIconSize = 16;
            closeIconMargin = 4;
            obj.CloseImage.Position = [max(closeIconMargin, contentWidth - closeIconSize - closeIconMargin), ...
                                       max(closeIconMargin, (headerHeight - closeIconSize) / 2), ...
                                       closeIconSize, closeIconSize];
        end

        %-----------------------------------------------------------------%
        function resizeDownloadProgressBars(obj)
            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if isempty(task) || isempty(task.ProgressTrack) || ~isvalid(task.ProgressTrack)
                    continue
                end
                obj.updateProgressScale(task)
            end
        end

        %-----------------------------------------------------------------%
        function updateProgressScale(~, task)
            if isempty(task.ProgressTrack) || ~isvalid(task.ProgressTrack)
                return
            end
            trackSize = task.ProgressTrack.InnerPosition;
            trackWidth = max(0, trackSize(3));
            trackHeight = max(1, trackSize(4));
            task.ProgressFill.Position = [0, 0, task.ProgressFraction * trackWidth, trackHeight];
            markerWidth = 1;
            markerXPositions = round((0:4) / 4 * max(0, trackWidth - markerWidth));
            for markerIndex = 1:numel(task.ProgressMarkers)
                marker = task.ProgressMarkers(markerIndex);
                if ~isempty(marker) && isvalid(marker)
                    marker.Position = [markerXPositions(markerIndex), 0, markerWidth, trackHeight];
                end
            end
        end

        %-----------------------------------------------------------------%
        function updateDownloadAvatar(obj)
            activeCount = 0;
            receivedBytes = 0;
            totalBytes = 0;
            transferRate = 0;

            for taskID = 1:numel(obj.DownloadTasks)
                task = obj.DownloadTasks{taskID};
                if isempty(task) || ~strcmp(task.LifecycleState, 'active')
                    continue
                end
                activeCount = activeCount + 1;
                if isfinite(task.ReceivedBytes)
                    receivedBytes = receivedBytes + max(0, double(task.ReceivedBytes));
                end
                if ~isempty(task.TotalBytes) && isfinite(task.TotalBytes) && task.TotalBytes > 0
                    totalBytes = totalBytes + double(task.TotalBytes);
                end
                if isfinite(task.TransferRate) && task.TransferRate > 0
                    transferRate = transferRate + double(task.TransferRate);
                end
            end

            percentage = 0;
            if totalBytes > 0
                percentage = min(100, receivedBytes / totalBytes * 100);
            end
            state = struct('level', avatarLevel(percentage), ...
                           'inProgress', activeCount > 0, ...
                           'ballCount', activeCount, ...
                           'speedRadiansPerSecond', transferRate / 1024^2 * 2 * pi);
            if isequal(state, obj.AvatarState)
                return
            end
            obj.AvatarState = state;
            if obj.AvatarHTMLReady && ~isempty(obj.AvatarHTML) && isvalid(obj.AvatarHTML)
                obj.AvatarHTML.Data = state;
            end
        end
    end


    methods (Access = private)
        %-----------------------------------------------------------------%
        function [finalPath, cancelled] = resolveFinalPath(obj, url)
            cancelled = false;
            fileName = filenameFromURL(url);
            if strcmp(obj.executionMode, 'webApp')
                if isempty(strtrim(obj.TargetPath)) || ~isfolder(obj.TargetPath)
                    error('ui:DownloadPanel:missingTargetPath', ...
                          'TargetPath must be an existing folder in webApp mode.')
                end
                finalPath = fullfile(obj.TargetPath, fileName);
                return
            end

            defaultName = fileName;
            if ~isempty(strtrim(obj.TargetPath))
                defaultName = fullfile(obj.TargetPath, fileName);
            end
            [selectedName, selectedFolder] = uiputfile('*.*', '', defaultName);
            if isequal(selectedName, 0)
                finalPath = '';
                cancelled = true;
                return
            end
            figure(obj.UIFigure)
            finalPath = fullfile(selectedFolder, selectedName);
        end
    end


    % Static helpers used for validation and execution-mode-independent paths.
    methods (Static, Access = private)
        %-----------------------------------------------------------------%
        function setExecutionModeValue(obj, value)
            obj.executionMode = value;
        end
    end


    % Public property validation.
    methods
        %-----------------------------------------------------------------%
        function set.executionMode(obj, value)
            % SET.EXECUTIONMODE Validate and assign the execution mode.
            value = char(value);
            allowedValues = {'webApp', 'desktopStandaloneApp', 'MATLABEnvironment'};
            if ~ismember(value, allowedValues)
                error('ui:DownloadPanel:invalidExecutionMode', ...
                      'executionMode must be webApp, desktopStandaloneApp, or MATLABEnvironment.')
            end
            obj.executionMode = value;
        end

        %-----------------------------------------------------------------%
        function set.CollisionPolicy(obj, value)
            % SET.COLLISIONPOLICY Validate the target-conflict policy.
            value = char(value);
            allowedValues = {'askInRow', 'overwrite', 'uniqueName', 'reject'};
            if ~ismember(value, allowedValues)
                error('ui:DownloadPanel:invalidCollisionPolicy', ...
                      'CollisionPolicy is not supported.')
            end
            obj.CollisionPolicy = value;
        end

        %-----------------------------------------------------------------%
        function set.PartialConflictPolicy(obj, value)
            % SET.PARTIALCONFLICTPOLICY Validate the partial-file policy.
            value = char(value);
            allowedValues = {'askInRow', 'resume', 'restart', 'cancel'};
            if ~ismember(value, allowedValues)
                error('ui:DownloadPanel:invalidPartialConflictPolicy', ...
                      'PartialConflictPolicy is not supported.')
            end
            obj.PartialConflictPolicy = value;
        end
    end
end

%-----------------------------------------------------------------%
function figureHandle = findFigure(parentContainer)
if isa(parentContainer, 'matlab.ui.Figure')
    figureHandle = parentContainer;
else
    figureHandle = ancestor(parentContainer, 'figure');
end
end

%-----------------------------------------------------------------%
function sourcePath = avatarHTMLPath()
sourcePath = fullfile(fileparts(mfilename('fullpath')), 'html', 'downloadAvatar.html');
end

%-----------------------------------------------------------------%
function sourcePath = closeIconPath()
sourcePath = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                     'icons', 'close-16px-red.svg');
end

%-----------------------------------------------------------------%
function value = eventProperty(event, propertyNames)
value = '';
for propertyIndex = 1:numel(propertyNames)
    if isprop(event, propertyNames{propertyIndex})
        propertyValue = event.(propertyNames{propertyIndex});
        if ischar(propertyValue) || (isstring(propertyValue) && isscalar(propertyValue))
            value = char(propertyValue);
        else
            value = propertyValue;
        end
        return
    end
end
end

%-----------------------------------------------------------------%
function value = shortTaskID()
value = char(matlab.lang.internal.uuid());
value = regexprep(value, '-', '');
value = value(1:min(8, numel(value)));
end

%-----------------------------------------------------------------%
function partialPath = findPartialPath(folderPath, fileName)
partialPath = '';
if isempty(folderPath) || ~isfolder(folderPath)
    return
end

entries = dir(fullfile(folderPath, ['*_', fileName, '.part']));
if isempty(entries)
    entries = dir(fullfile(folderPath, ['*_', fileName, '.part.chunk']));
    for entryIndex = 1:numel(entries)
        entries(entryIndex).name = erase(entries(entryIndex).name, '.chunk');
    end
end
if isempty(entries)
    return
end

[~, newestIndex] = max([entries.datenum]);
partialPath = fullfile(folderPath, entries(newestIndex).name);
end

%-----------------------------------------------------------------%
function moveFileWithFallback(sourcePath, destinationPath)
[moved, message] = movefile(sourcePath, destinationPath, 'f');
if moved
    return
end

[copied, copyMessage] = copyfile(sourcePath, destinationPath, 'f');
if ~copied
    error('ui:DownloadPanel:fileTransferFailed', ...
          'Could not move or copy "%s" to "%s": %s %s', ...
          sourcePath, destinationPath, message, copyMessage)
end
delete(sourcePath)
end

%-----------------------------------------------------------------%
function deleteIfExists(filePath)
if isempty(filePath)
    return
end
if isfile(filePath) || isfolder(filePath)
    delete(filePath)
end
end

%-----------------------------------------------------------------%
function restoreBackup(task)
if ~isfield(task, 'BackupPath') || isempty(task.BackupPath) || ~isfile(task.BackupPath)
    return
end
if isfile(task.FinalPath) || isfolder(task.FinalPath)
    return
end
try
    moveFileWithFallback(task.BackupPath, task.FinalPath)
catch
end
end

%-----------------------------------------------------------------%
function exists = pathExists(filePath)
exists = isfile(filePath) || isfolder(filePath);
end

%-----------------------------------------------------------------%
function ensureFolder(folderPath)
if isempty(folderPath)
    error('ui:DownloadPanel:missingTempPath', 'TempPath must not be empty.')
end
if ~isfolder(folderPath)
    [created, message] = mkdir(folderPath);
    if ~created && ~isfolder(folderPath)
        error('ui:DownloadPanel:tempPathUnavailable', '%s', message)
    end
end
end

%-----------------------------------------------------------------%
function validateDownloader(downloader)
if isempty(downloader)
    error('ui:DownloadPanel:invalidDownloader', 'DownloaderFactory returned an empty value.')
end
requiredMethods = {'start', 'pause', 'resume', 'stop'};
for methodIndex = 1:numel(requiredMethods)
    if ~ismethod(downloader, requiredMethods{methodIndex})
        error('ui:DownloadPanel:invalidDownloader', ...
              'DownloaderFactory result does not implement %s.', requiredMethods{methodIndex})
    end
end
requiredProperties = {'ProgressFcn', 'CompletedFcn', 'ErrorFcn'};
for propertyIndex = 1:numel(requiredProperties)
    if ~isprop(downloader, requiredProperties{propertyIndex})
        error('ui:DownloadPanel:invalidDownloader', ...
              'DownloaderFactory result does not expose %s.', requiredProperties{propertyIndex})
    end
end
end

%-----------------------------------------------------------------%
function value = uniqueTargetPath(filePath)
[folderPath, baseName, extension] = fileparts(filePath);
value = filePath;
index = 1;
while isfile(value) || isfolder(value)
    value = fullfile(folderPath, sprintf('%s (%d)%s', baseName, index, extension));
    index = index + 1;
end
end

%-----------------------------------------------------------------%
function value = filenameFromURL(url)
value = 'download';
try
    pathSegments = matlab.net.URI(url).Path;
    if ~isempty(pathSegments) && strlength(pathSegments(end)) > 0
        value = char(pathSegments(end));
    end
catch
end
value = regexprep(value, '[\\/:*?"<>|]', '_');
if isempty(value) || strcmp(value, '.') || strcmp(value, '..')
    value = 'download';
end
end

%-----------------------------------------------------------------%
function text = progressText(receivedBytes, totalBytes, elapsedSeconds, transferRate)
receivedText = formatBytes(receivedBytes);
totalText = '-';
totalSizeText = '-';
if ~isempty(totalBytes) && totalBytes > 0
    totalText = formatBytes(totalBytes);
    totalSizeText = formatTotalBytes(totalBytes);
end
if elapsedSeconds < 10
    elapsedText = '- s';
    remainingText = '- s';
else
    elapsedText = formatDuration(elapsedSeconds);
    remainingText = '- s';
    if ~isempty(totalBytes) && totalBytes > 0 && isfinite(transferRate) && transferRate > 0
        remainingText = formatDuration(max(0, double(totalBytes) - double(receivedBytes)) / transferRate);
    end
end
text = sprintf('%s / %s (%s) | Elapsed: %s | Remaining: %s', ...
               receivedText, totalText, totalSizeText, elapsedText, remainingText);
end

%-----------------------------------------------------------------%
function text = formatBytes(value)
if isempty(value) || ~isscalar(value) || ~isfinite(value)
    text = 'unknown';
    return
end
value = double(value);
digits = sprintf('%.0f', max(0, value));
firstGroupLength = mod(numel(digits), 3);
if firstGroupLength == 0
    firstGroupLength = 3;
end
groupCount = 1 + floor((numel(digits) - firstGroupLength) / 3);
groups = cell(1, groupCount);
groups{1} = digits(1:firstGroupLength);
for groupIndex = 2:groupCount
    startIndex = firstGroupLength + (groupIndex - 2) * 3 + 1;
    groups{groupIndex} = digits(startIndex:startIndex + 2);
end
text = strjoin(groups, ' ');
end

%-----------------------------------------------------------------%
function text = formatTotalBytes(value)
value = double(value);
scales = [1024^3, 1024^2, 1024];
names = {'GBytes', 'MBytes', 'kBytes'};
unitIndex = find(value >= scales, 1, 'first');
if isempty(unitIndex)
    unitIndex = numel(scales);
end
text = sprintf('%.0f %s', max(1, round(value / scales(unitIndex))), names{unitIndex});
end

%-----------------------------------------------------------------%
function text = formatDuration(seconds)
seconds = max(0, round(double(seconds)));
if seconds < 60
    text = sprintf('%.0f s', seconds);
    return
end
minutes = floor(seconds / 60);
remainingSeconds = mod(seconds, 60);
if minutes < 60
    if remainingSeconds == 0
        text = sprintf('%.0f min', minutes);
    else
        text = sprintf('%.0f min %.0f s', minutes, remainingSeconds);
    end
    return
end
hours = floor(minutes / 60);
remainingMinutes = mod(minutes, 60);
if remainingMinutes == 0
    text = sprintf('%.0f h', hours);
else
    text = sprintf('%.0f h %.0f min', hours, remainingMinutes);
end
end

%-----------------------------------------------------------------%
function level = avatarLevel(percentage)
if percentage <= 0
    level = 0;
elseif percentage >= 90
    level = 10;
else
    level = ceil(percentage / 10);
end
end

%-----------------------------------------------------------------%
function info = publicTaskInfo(task)
info = struct('ID', task.ID, ...
              'TaskID', task.TaskID, ...
              'URL', task.URL, ...
              'FileName', task.FileName, ...
              'TempFolder', task.TempFolder, ...
              'TargetFolder', task.TargetFolder, ...
              'FinalPath', task.FinalPath, ...
              'PartialPath', task.PartialPath, ...
              'BackupPath', task.BackupPath, ...
              'ReceivedBytes', task.ReceivedBytes, ...
              'TotalBytes', task.TotalBytes, ...
              'LifecycleState', task.LifecycleState);
end

%-----------------------------------------------------------------%
function invokeCallback(callback, varargin)
if isempty(callback)
    return
end
try
    callback(varargin{:})
catch
end
end

%-----------------------------------------------------------------%
function value = ternary(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end
