function mustBeBuiltInComponent(x)
%MUSTBEBUILTINCOMPONENT

% Author.: Eric Magalhães Delgado
% Date...: July 27, 2023
% Version: 1.00

    warning('off', 'MATLAB:structOnObject')

    try
        BuiltInComponentsList = [{'matlab.ui.container.internal.AppContainer'}; ...
                                 struct(appdesigner.internal.application.getComponentAdapterMap()).serialization.keys'];
    catch
        BuiltInComponentsList = {'matlab.ui.container.internal.AppContainer', ...
                                 'matlab.ui.Figure',                       ...
                                 'matlab.ui.container.ButtonGroup',        ...
                                 'matlab.ui.container.CheckBoxTree',       ...
                                 'matlab.ui.container.ContextMenu',        ...
                                 'matlab.ui.container.GridLayout',         ...
                                 'matlab.ui.container.Menu',               ...
                                 'matlab.ui.container.Panel',              ...
                                 'matlab.ui.container.Tab',                ...
                                 'matlab.ui.container.TabGroup',           ...
                                 'matlab.ui.container.Toolbar',            ...
                                 'matlab.ui.container.Tree',               ...
                                 'matlab.ui.container.TreeNode',           ...
                                 'matlab.ui.container.toolbar.PushTool',   ...
                                 'matlab.ui.container.toolbar.ToggleTool', ...
                                 'matlab.ui.control.Button',               ...
                                 'matlab.ui.control.CheckBox',             ...
                                 'matlab.ui.control.DatePicker',           ...
                                 'matlab.ui.control.DiscreteKnob',         ...
                                 'matlab.ui.control.DropDown',             ...
                                 'matlab.ui.control.EditField',            ...
                                 'matlab.ui.control.Gauge',                ...
                                 'matlab.ui.control.HTML',                 ...
                                 'matlab.ui.control.Hyperlink',            ...
                                 'matlab.ui.control.Image',                ...
                                 'matlab.ui.control.Knob',                 ...
                                 'matlab.ui.control.Label',                ...
                                 'matlab.ui.control.Lamp',                 ...
                                 'matlab.ui.control.LinearGauge',          ...
                                 'matlab.ui.control.ListBox',              ...
                                 'matlab.ui.control.NinetyDegreeGauge',    ...
                                 'matlab.ui.control.NumericEditField',     ...
                                 'matlab.ui.control.RadioButton',          ...
                                 'matlab.ui.control.RockerSwitch',         ...
                                 'matlab.ui.control.SemicircularGauge',    ...
                                 'matlab.ui.control.Slider',               ...
                                 'matlab.ui.control.Spinner',              ...
                                 'matlab.ui.control.StateButton',          ...
                                 'matlab.ui.control.Switch',               ...
                                 'matlab.ui.control.Table',                ...
                                 'matlab.ui.control.TextArea',             ...
                                 'matlab.ui.control.ToggleButton',         ...
                                 'matlab.ui.control.ToggleSwitch',         ...
                                 'matlab.ui.control.UIAxes'};
    end
    mustBeMember(class(x), BuiltInComponentsList)
end