function [methodinfo,structs,enuminfo,ThunkLibName]=IQWrapperProto
%IQWRAPPERPROTO Create structures to define interfaces found in 'IQWrapper'.

%This function was generated by loadlibrary.m parser version  on Tue Mar 24 14:03:36 2026
%perl options:'IQWrapper.i -outfile=IQWrapperProto.m -thunkfile=IQWrapper_thunk_pcwin64.c -header=IQWrapper.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'IQWrapper_thunk_pcwin64');
%  int IQWrapper_Load_Library ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='IQWrapper_Load_Library'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  void IQWrapper_Unload_Library ( void ); 
fcns.thunkname{fcnNum}='voidvoidThunk';fcns.name{fcnNum}='IQWrapper_Unload_Library'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int IQWrapper_OpenFile ( char * fname , int * nBlocks ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrThunk';fcns.name{fcnNum}='IQWrapper_OpenFile'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int32Ptr'};fcnNum=fcnNum+1;
%  void IQWrapper_CloseFile ( void ); 
fcns.thunkname{fcnNum}='voidvoidThunk';fcns.name{fcnNum}='IQWrapper_CloseFile'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int IQWrapper_dBm_NextBlock ( CapturedRawBuffer_C * dBm_Buffer , float * dBm , int * BlockNumber , int * length ); 
fcns.thunkname{fcnNum}='int32voidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='IQWrapper_dBm_NextBlock'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'CapturedRawBuffer_CPtr', 'singlePtr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int IQWrapper_MoreBlocksAvailable ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='IQWrapper_MoreBlocksAvailable'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int IQWrapper_Get_DLL_Version ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='IQWrapper_Get_DLL_Version'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
structs.CapturedRawBuffer_C.packing=1;
structs.CapturedRawBuffer_C.members=struct('latitude', 'double', 'longitude', 'double', 'altitude', 'double', 'year', 'uint16', 'month', 'uint16', 'dayOfWeek', 'uint16', 'day', 'uint16', 'hour', 'uint16', 'minute', 'uint16', 'second', 'uint16', 'milliseconds', 'uint16', 'packet_timeStamp_sec', 'uint32', 'packet_timeStamp_psec', 'uint64', 'ext_NoiseLevelOffset', 'double', 'ext_Tech', 'int32', 'ext_Band', 'int32', 'ext_Channel', 'int32', 'ext_freq', 'double', 'ext_ReducedFreqSpan_MHz', 'double', 'ext_FullFreqSpan_MHz', 'double', 'ext_ResBw_kHz', 'double', 'ext_Decimation', 'int32', 'ext_SamplesPerPacket', 'int32', 'ext_PacketsPerBlock', 'int32', 'ext_ppm', 'double', 'ext_NominalGain', 'int32', 'RecordSize', 'int32', 'Buffer_nElems', 'int32', 'ext_SCS_kHz', 'int32', 'DuplexMode', 'int32');
methodinfo=fcns;